name: 'GitHub App Auth'
description: 'GitHub Action which gets an auth token for a repo or organization via a GitHub app installation'
author: 'David Sanders'

inputs:
  creds:
    description: 'A credential bundle for the GitHub app to generate the token for'
    required: true
  org:
    description: 'The organization for an org-scoped token'
    required: false
  owner:
    description: 'The repo owner for a repo-scoped token'
    required: false
  repo:
    description: 'The repo name for a repo-scoped token'
    required: false
  export-git-user:
    description: 'Export environment variables which set the git user to the GitHub app user'
    required: false

outputs:
  token:
    description: 'GitHub installation access token'

runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
